<a href="https://colab.research.google.com/github/Shahupatil2407/Machine-Learning/blob/main/Regularization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("/content/Advertising.csv")

In [3]:
df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [4]:
X = df.drop('sales', axis=1)
y = df['sales']

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
poly_converter = PolynomialFeatures(degree=3, include_bias=False)

In [9]:
poly_features = poly_converter.fit_transform(X)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [12]:
from sklearn.preprocessing import StandardScaler


In [13]:
scaler = StandardScaler()

In [14]:
X_train = scaler.fit_transform(X_train)

In [15]:
X_test = scaler.fit_transform(X_test)

In [17]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [18]:
X_test[0]

array([-0.70089624,  1.77066512,  0.73398854, -0.813449  ,  0.160092  ,
       -0.10365708,  2.2314938 ,  1.47174292,  0.36412244, -0.76998264,
       -0.40201033, -0.49954437,  0.5041369 ,  0.38482416, -0.04050793,
        2.56792918,  1.8877582 ,  0.77106615,  0.07159576])

***Ridge Regression ***

In [20]:
from sklearn.linear_model import Ridge

In [21]:
model = Ridge(alpha=10)

In [22]:
model.fit(X_train, y_train)

Ridge(alpha=10)

In [23]:
predictedions = model.predict(X_test)

In [24]:
predictedions

array([14.72040305, 19.68162602, 12.77344563, 17.13398747,  9.94195003,
        9.09273492, 20.53255998, 17.5642862 , 11.20240863, 20.23898279,
       11.31581283, 14.23554699, 12.98024107, 23.70241564, 19.68719787,
       10.75211826, 13.43050956, 10.11553321,  9.83940033, 21.87053342,
        9.29351427, 19.44860351, 28.37065001, 25.16018616, 10.10302856,
       12.52511663, 21.26203177, 10.34552979, 13.07082093, 10.2295026 ,
       10.36119434, 20.31219195, 11.46768434,  8.94165105, 18.31818676,
       10.29147399, 11.12043731, 10.44374713,  9.71463738, 11.64518818,
       12.90784926, 11.28592455, 11.85706836,  9.4709617 , 12.30076777,
       11.32095318,  9.05923001, 15.76329188, 13.65980715, 22.98481942,
       11.8378082 , 13.71101394, 15.28617314, 12.27189133, 12.46062141,
        8.26891502, 25.80885832, 11.40749321, 17.96986163, 15.81533423])

In [25]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [28]:
MAE = mean_absolute_error(y_test, predictedions)
MAE

0.9670410375853883

In [29]:
MSE = mean_squared_error(y_test, predictedions)
MSE

1.776252295047126

In [30]:
RMSE = np.sqrt(MSE)
RMSE

np.float64(1.332761154538624)

In [32]:
from sklearn.linear_model import RidgeCV

In [33]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring='neg_mean_absolute_error')

In [34]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(scoring='neg_mean_absolute_error')

In [35]:
ridge_cv_model.alpha_

np.float64(0.1)

In [37]:
test_prediction = ridge_cv_model.predict(X_test)

In [38]:
MAE = mean_absolute_error(y_test, test_prediction)
MAE

0.9873965312426425

In [39]:
MSE = mean_squared_error(y_test, test_prediction)
MSE

1.3634508669511087

In [40]:
RMSE = np.sqrt(MSE)
RMSE

np.float64(1.1676689886055502)

**Lasso Regression** - Least Absolute Shrinkage and Selection Operator

In [41]:
from sklearn.linear_model import LassoCV

In [44]:
lasso_cv_model = LassoCV(eps=0.01,n_alphas=100,cv=5, max_iter=1000000)

In [45]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, eps=0.01, max_iter=1000000)

In [46]:
lasso_cv_model.alpha_

np.float64(0.049430709092258315)

In [47]:
predictions = lasso_cv_model.predict(X_test)

In [48]:
MAE = mean_absolute_error(y_test, predictions)
MAE

0.9734596873927972

In [49]:
MSE = mean_squared_error(y_test, predictions)
MSE

1.5694053351572839

In [50]:
RMSE = np.sqrt(MSE)
RMSE

np.float64(1.2527590890339946)

In [51]:
lasso_cv_model.coef_

array([ 2.35600233,  0.21183181,  0.        , -0.        ,  3.78675114,
       -0.        ,  0.        ,  0.0624318 ,  0.        , -1.01152151,
       -0.        , -0.        ,  0.        ,  0.        , -0.        ,
        0.        ,  0.        ,  0.        ,  0.        ])

**Elastic Net**

In [52]:
from sklearn.linear_model import ElasticNetCV

In [53]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1], eps = 0.001, n_alphas=100, max_iter=1000000)

In [54]:
elastic_model.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [55]:
model_prediction = elastic_model.predict(X_test)

In [56]:
model_prediction

array([15.14418529, 19.92467734, 13.32654403, 17.78177413,  9.31969517,
        8.28970106, 20.66855714, 18.04269516, 11.49949176, 20.48184455,
       10.80134454, 14.85815331, 12.79734024, 23.71393203, 20.02167198,
       10.5041003 , 13.10812809, 10.47493725,  9.81188189, 21.99284978,
        8.39710616, 19.96871732, 27.44614812, 24.74739054, 10.39226807,
       12.46593558, 21.31364617, 10.47984029, 13.50316812,  9.66569631,
        9.81928703, 20.52752114, 11.89695128,  8.12895401, 18.84552631,
       10.60825922, 11.53663135, 10.86845622,  8.55298573, 11.88618974,
       13.80815855, 11.5410171 , 12.32178653,  8.71984305, 12.64938601,
       11.57875791,  7.40894931, 15.98634069, 13.95052882, 23.09411427,
       11.63589989, 13.83649432, 15.26811737, 12.96000061, 12.37953832,
        6.98887565, 25.48461539, 10.92565279, 18.15719863, 16.37625528])

In [57]:
MAE = mean_absolute_error(y_test, model_prediction)
MAE

0.972393914539185

In [59]:
MSE = mean_squared_error(y_test, model_prediction)
print("Mean Squared Error:", MSE)

Mean Squared Error: 1.3386734791778678


In [60]:
RMSE = np.sqrt(MSE)
RMSE

np.float64(1.1570105786801899)

In [61]:
elastic_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [63]:
elastic_model.l1_ratio_

np.float64(1.0)